/* eslint-disable unicorn/filename-case, import/no-unresolved */
import xoSpace from "eslint-config-xo/space";
import xoTypeScript from "eslint-config-xo-typescript";
import prettierPluginRecommended from "eslint-plugin-prettier/recommended";
import tseslint from "typescript-eslint";
import base from "./lint-rulesets/base.js";
import importRules from "./lint-rulesets/import.js";
import node from "./lint-rulesets/node.js";
import ts from "./lint-rulesets/ts.js";
import unicorn from "./lint-rulesets/unicorn.js";
import { typescriptExtensions } from "./lint-rulesets/util.js";

// See https://github.com/xojs/eslint-config-xo-typescript/issues/88
xoTypeScript[1].files = [`**/*.{${typescriptExtensions.join(",")}}`];

// Note that order matters, as some configs overwrite rules + settings generated by others
export default tseslint.config(
  ...xoSpace,
  ...xoTypeScript,
  ...base,
  ...unicorn,
  ...importRules,
  ...ts,
  ...node,
  prettierPluginRecommended,
);
