import path from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import xoSpaceBrowser from "eslint-config-xo/space/browser";
import xoTypeScript from "eslint-config-xo-typescript";
import prettierPluginRecommended from "eslint-plugin-prettier/recommended";
import tseslint from "typescript-eslint";
import base from "./lint-rulesets/base.js";
import cssModules from "./lint-rulesets/css-modules.js";
import importRules from "./lint-rulesets/import.js";
import react from "./lint-rulesets/react.js";
import ts from "./lint-rulesets/ts.js";
import unicorn from "./lint-rulesets/unicorn.js";
import { typescriptExtensions } from "./lint-rulesets/util.js";

// Required to load old extend formats
// see https://eslint.org/docs/latest/use/configure/migration-guide
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({ baseDirectory: __dirname });

// See https://github.com/xojs/eslint-config-xo-typescript/issues/88
xoTypeScript[1].files = [`**/*.{${typescriptExtensions.join(",")}}`];

// Note that order matters, as some configs overwrite rules + settings generated by others
export default tseslint.config(
  ...xoSpaceBrowser,
  ...xoTypeScript,
  ...compat.extends("xo-react/space"),
  ...base,
  ...unicorn,
  ...importRules,
  ...ts,
  ...react,
  ...cssModules,
  prettierPluginRecommended,
);
