/* eslint-disable unicorn/filename-case, import/no-unresolved */
import { resolveFlatConfig } from "@leancodepl/resolve-eslint-flat-config";
import xoSpaceBrowser from "eslint-config-xo/space/browser";
import xoReact from "eslint-config-xo-react";
import xoTypeScript from "eslint-config-xo-typescript";
import prettierPluginRecommended from "eslint-plugin-prettier/recommended";
import tseslint from "typescript-eslint";
import base from "./lint-rulesets/base.js";
import cssModules from "./lint-rulesets/css-modules.js";
import importRules from "./lint-rulesets/import.js";
import react from "./lint-rulesets/react.js";
import ts from "./lint-rulesets/ts.js";
import unicorn from "./lint-rulesets/unicorn.js";
import { typescriptExtensions } from "./lint-rulesets/util.js";

// See https://github.com/xojs/eslint-config-xo-typescript/issues/88
xoTypeScript[1].files = [`**/*.{${typescriptExtensions.join(",")}}`];

// Note that order matters, as some configs overwrite rules + settings generated by others
export default resolveFlatConfig(
  tseslint.config(
    ...xoSpaceBrowser,
    ...xoTypeScript,
    ...xoReact,
    ...base,
    ...unicorn,
    ...importRules,
    ...ts,
    ...react,
    ...cssModules,
    prettierPluginRecommended,
  ),
);
